# acme-cert-upload/tasks/main.yml

---
- name: upload domain certs directory for {{ domain }}
  copy:
    src: '{{ work_directory }}/{{ domain }}'
    dest: '{{ remote_directory }}/{{ domain }}'
  tags:
    - acme-cert-upload