# linux-install-lsyncd/tasks/ubuntu.yml

---
- name: ubuntu - install lsyncd
  apt:
    name:
      - rsync
      - lsyncd
    state: latest
    update_cache: yes
  notify: 'restarted and enabled lsyncd'
  tags:
    - linux-install-lsyncd