# linux-install-gitlab-runner/tasks/debian.yml

---
- name: debian - install gitlab-runner
  apt:
    deb: '{{ gitlab_runner_apt_package }}'
  notify: 'restarted and enabled gitlab-runner'
  tags:
    - linux-install-gitlab-runner