# linux-install-docker/tasks/centos.yml

---
- name: centos - add yum repository
  get_url:
    url: '{{ docker_yum_repository_centos }}'
    dest: '/etc/yum.repos.d/docker.repo'
  tags:
    - linux-install-docker


- name: centos - install docker
  yum:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
  tags:
    - linux-install-docker