# linux-install-docker/tasks/main.yml

---
- name: gather facts
  setup:
    gather_subset:
      - '!all'
  tags:
    - linux-install-docker


- name: enable params in sysctl
  sysctl:
    name: '{{ item }}'
    sysctl_file: '/etc/sysctl.d/99-docker.conf'
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - 'net.ipv4.ip_forward'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
  tags:
    - linux-install-docker


- name: including tasks for OS
  include_tasks: '{{ ansible_distribution|lower }}.yml'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
  tags:
    - linux-install-docker


- name: download docker-compose binary
  get_url:
    url: '{{ docker_compose_binary }}'
    dest: '/usr/local/bin/docker-compose'
    mode: 0755
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
  tags:
    - linux-install-docker


- name: create symlink for docker-compose
  file:
    src: '/usr/local/bin/docker-compose'
    dest: '/usr/bin/docker-compose'
    state: link
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
  tags:
    - linux-install-docker