# linux-install-powerdns/tasks/centos.yml

---
- name: centos - install epel-release
  yum:
    name:
      - epel-release
    state: latest
    update_cache: yes
  tags:
    - linux-install-powerdns


- name: centos - install yum-plugin-priorities for version 6/7
  yum:
    name:
      - yum-plugin-priorities
    state: latest
    update_cache: yes
  when: ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7'
  tags:
    - linux-install-powerdns


- name: centos - add yum epository
  get_url:
    url: '{{ powerdns_yum_repository_centos }}'
    dest: '/etc/yum.repos.d/powerdns.repo'
  tags:
    - linux-install-powerdns


- name: centos - install powerdns
  yum:
    name: pdns
    state: latest
    update_cache: yes
  tags:
    - linux-install-powerdns