# linux-install-nginx/tasks/centos.yml

---
- name: centos - install required packages
  yum:
    name: 
      - yum-utils
    state: latest
    update_cache: yes
  tags:
    - linux-install-nginx


- name: centos - add yum repository
  template:
    src: 'nginx.repo.j2'
    dest: '/etc/yum.repos.d/nginx.repo'
  tags:
    - linux-install-nginx


- name: centos - install nginx
  yum:
    name: 
      - nginx
    state: latest
    update_cache: yes
  notify: 'restarted and enabled nginx'
  tags:
    - linux-install-nginx