# linux-install-nginx/tasks/main.yml

---
- name: gather facts
  setup:
    gather_subset:
      - '!all'
  tags:
    - linux-install-nginx


- name: including tasks for OS
  include_tasks: '{{ ansible_distribution|lower }}.yml'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
  tags:
    - linux-install-nginx