# linux-install-nginx/tasks/ubuntu.yml

---
- name: ubuntu - install required packages
  apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
    force_apt_get: yes
    state: latest
    update_cache: yes
  tags:
    - linux-install-nginx


- name: ubuntu - add official repository GPG key
  apt_key:
    id: '{{ nginx_repository_gpg_fingerprint }}'
    url: '{{ nginx_repository_gpg_key }}'
    state: present
  tags:
    - linux-install-nginx


- name: ubuntu - add apt repository
  apt_repository:
    repo: '{{ nginx_apt_repository_ubuntu }}'
    filename: 'nginx'
    state: present
    update_cache: no
  tags:
    - linux-install-nginx


- name: ubuntu - install nginx
  apt:
    name: 
      - nginx
    state: latest
    update_cache: yes
  notify: 'restarted and enabled nginx'
  tags:
    - linux-install-nginx