# acme-cert-delete/tasks/main.yml

---
- name: deleting domain certs directory for {{ domain }}
  file:
    dest: '{{ item }}'
    state: absent
  with_items:
    - '{{ work_directory }}/{{ domain }}'
    - '{{ csr_directory }}'
  run_once: yes
  delegate_to: localhost
  tags:
    - acme-cert-delete